encoder-embed-dim-subtransformer: 512
decoder-embed-dim-subtransformer: 640

encoder-ffn-embed-dim-all-subtransformer: [2048, 3072, 3072, 2048, 1024, 1024]
decoder-ffn-embed-dim-all-subtransformer: [1024, 2048, 2048, 2048]

encoder-layer-num-subtransformer: 6
decoder-layer-num-subtransformer: 4

encoder-self-attention-heads-all-subtransformer: [4, 8, 4, 4, 8, 4]
decoder-self-attention-heads-all-subtransformer: [4, 8, 8, 4]
decoder-ende-attention-heads-all-subtransformer: [8, 4, 4, 4]

decoder-arbitrary-ende-attn-all-subtransformer: [1, 2, 1, 1]

